-- SQL Migration for Instituto Suína
-- Generated from migracao_suina.xlsx

INSERT INTO public.noticias (title, slug, content, status, published_at) VALUES ('Noticias ee6024', 'noticias-ee6024', 'Secretaria de Meio Ambiente e Proteção Animal
A Secretaria Municipal de Meio Ambiente e Proteção Animal realizou na terça-feira (24/6), em parceria com o Instituto Suinã, o evento “Terra Viva – Oficina de Compostagem Doméstica”, que ensinou técnicas de compostagem para reduzir o desperdício, nutrir o solo e criar um ciclo sustentável em casa ou na comunidade. A oficina foi realizada no Viveiro Municipal, localizado no Parque Leon Feffer, e faz parte da programação do Junho EcoSustentável.
“A oficina foi muito enriquecedora e mostrou como é possível realizar um trabalho eficiente de compostagem em pequenos espaços. Este é o objetivo da nossa programação do Junho EcoSustentável: oferecer informação à população, para que mais pessoas incorporem esses hábitos ao seu cotidiano, contribuindo para a construção de uma cidade cada vez mais conectada à natureza e às práticas ambientalmente corretas”, comentou a secretária Patricia Cesare. 
A oficina foi ministrada pelas especialistas socioambientais no Instituto Suinã, Letícia Gonzaga e Larissa Neli. Elas ensinaram técnicas de vermicompostagem, que é o processo que utiliza minhocas para acelerar o processo de decomposição de resíduos orgânicos, transformando-os em húmus, um fertilizante natural rico em nutrientes. É uma forma eficaz e sustentável de reduzir o volume de lixo orgânico e produzir adubo de alta qualidade para jardins e plantas.
“Quando as pessoas fazem esse processo de compostagem, elas utilizam cascas de verduras, legumes e frutas para adubar as plantas e tornar a terra mais nutritiva. Isso contribui para a redução do volume de resíduos que são destinados aos aterros sanitários”, observa o chefe da Divisão de Recicláveis da Secretaria, Ricardo Moscatelli.
Programação
A programação do Junho EcoSustentável prosseguirá na quinta-feira (26/6), com a 4ª edição do Programa Seu Amigo Pet, em Taiaçupeba. O evento faz parte da programação do Junho EcoSustentável e um dos principais destaques da ação será o Mutirão de Castração de Animais, voltado exclusivamente a tutores de cães cadastrados no CadÚnico. As inscrições já foram realizadas pela Administração Regional de Taiçupeba, voltadas a tutores de pets do distrito. A previsão é de que sejam castrados 130 animais, entre machos e fêmeas. As cadelas serão atendidas pela manhã e os machos, à tarde. Os tutores devem levar seus pets na sede 2 da Administração Regional de Taiaçupeba, localizada na rua Virginia Eugênia Grisbach Auerbach, 49.

A Secretaria Municipal de Meio Ambiente e Proteção Animal realizou na terça-feira (24/6), em parceria com o Instituto Suinã, o evento “Terra Viva – Oficina de Compostagem Doméstica”, que ensinou técnicas de compostagem para reduzir o desperdício, nutrir o solo e criar um ciclo sustentável em casa ou na comunidade. A oficina foi realizada no Viveiro Municipal, localizado no Parque Leon Feffer, e faz parte da programação do Junho EcoSustentável.
“A oficina foi muito enriquecedora e mostrou como é possível realizar um trabalho eficiente de compostagem em pequenos espaços. Este é o objetivo da nossa programação do Junho EcoSustentável: oferecer informação à população, para que mais pessoas incorporem esses hábitos ao seu cotidiano, contribuindo para a construção de uma cidade cada vez mais conectada à natureza e às práticas ambientalmente corretas”, comentou a secretária Patricia Cesare. 
A oficina foi ministrada pelas especialistas socioambientais no Instituto Suinã, Letícia Gonzaga e Larissa Neli. Elas ensinaram técnicas de vermicompostagem, que é o processo que utiliza minhocas para acelerar o processo de decomposição de resíduos orgânicos, transformando-os em húmus, um fertilizante natural rico em nutrientes. É uma forma eficaz e sustentável de reduzir o volume de lixo orgânico e produzir adubo de alta qualidade para jardins e plantas.
“Quando as pessoas fazem esse processo de compostagem, elas utilizam cascas de verduras, legumes e frutas para adubar as plantas e tornar a terra mais nutritiva. Isso contribui para a redução do volume de resíduos que são destinados aos aterros sanitários”, observa o chefe da Divisão de Recicláveis da Secretaria, Ricardo Moscatelli.
Programação
A programação do Junho EcoSustentável prosseguirá na quinta-feira (26/6), com a 4ª edição do Programa Seu Amigo Pet, em Taiaçupeba. O evento faz parte da programação do Junho EcoSustentável e um dos principais destaques da ação será o Mutirão de Castração de Animais, voltado exclusivamente a tutores de cães cadastrados no CadÚnico. As inscrições já foram realizadas pela Administração Regional de Taiçupeba, voltadas a tutores de pets do distrito. A previsão é de que sejam castrados 130 animais, entre machos e fêmeas. As cadelas serão atendidas pela manhã e os machos, à tarde. Os tutores devem levar seus pets na sede 2 da Administração Regional de Taiaçupeba, localizada na rua Virginia Eugênia Grisbach Auerbach, 49.
“Nubea de Portas Abertas” acontece neste sábado (14/3), com Feira de Adoção de Passeio do Bem
Vice-prefeito e equipe de Saúde se reúnem com médicos da Unica para alinhar melhorias no atendimento
Treze representantes da sociedade civil são eleitos para a gestão 2026-2028 do COMAS
Centro de Controle de Zoonoses de Mogi das Cruzes recebe prêmio nacional da Fiocruz
Estudantes conhecem processo de tratamento de água na  primeira visita do Semae de Portas Abertas 2026
Siga-nos nas redes sociais
Prefeitura de Mogi das Cruzes
Av. Ver. Narciso Yague Guimarães, 277
Centro Cívico
CEP 08780-900
Mogi das Cruzes/SP
Segunda a sexta, das 8 às 17 horas
Telefone: 4798-5000
Serviços: 162
Ouvidoria: 156
Semae: 115
Saúde: 160
Guarda Municipal: 153', 'Publicado', now());
INSERT INTO public.noticias (title, slug, content, status, published_at) VALUES ('Noticias 1fcf9c', 'noticias-1fcf9c', 'Secretaria de Meio Ambiente e Proteção Animal
A Secretaria Municipal de Meio Ambiente e Proteção Animal participou, na quarta-feira (24/4), do 2º Encontro das Unidades de Conservação da Serra do Itapeti, promovido pelo Instituto Ecofuturo e realizado no Parque Municipal Chiquinho Veríssimo. O evento reuniu representantes das unidades e promoveu um debate sobre a gestão, os desafios e propostas de trabalho, buscando pontos de convergência e ações conjuntas que podem ser adotadas no futuro.
As unidades de conservação da Serra do Itapeti são o Parque Municipal Chiquinho Veríssimo, localizado no alto da serra e administrado pela Prefeitura de Mogi das Cruzes; a Reserva Particular do Patrimônio Natural (RPPN) do Botujuru, administrada pelo Instituto Ecofuturo; e três áreas gerenciadas pelo governo paulista - a Estação Ecológica do Itapeti, a Área de Proteção Ambiental da Várzea do Tietê e a Área de Proteção Ambiental (APA) da Serra do Itapeti, que engloba todas as reservas.
A APA da Serra do Itapeti possui 5.138,94 hectares de área, dos quais 97% estão no município de Mogi das Cruzes. A área foi reconhecida em 2018, pelo Governo do Estado, e sua conservação e fiscalização compete aos órgãos estaduais, como a Fundação Florestal e a Polícia Ambiental.
Participaram do encontro secretária municipal de Meio Ambiente e Proteção Ambiental, Ionara Fernandes; o secretário-adjunto Daniel Teixeira de Lima; o diretor de sustentabilidade do Instituto Ecofuturo, Paulo Groke; a diretora da Fundação Florestal, Lucila Manzatti; as gestoras da Estação Ecológica do Itapeti, Mônica Gomes de Oliveira, e da RPPN Botujuru, Julia Krahenbuhl, além das professoras Maria Santina e Renata Scabbia (UMC). Também compareceram o comandante Gurgel e o tenente Edson, da Polícia Ambiental.
Ao longo do evento foram abordados temas como “Iniciativas municipais de Conservação na Serra do Itapeti”, “A participação da sociedade na gestão de Unidades de Conservação”, “Mogi Por Dentro na Serra do Itapeti: caminhos de um desenvolvimento estratégico e participativo do turismo local”, “Educação Ambiental na Estação Ecológica de Itapeti”, “A importância da pesquisa científica e a parceria com as universidades” e “A iniciativa privada na conservação de áreas naturais”, finalizando com um diálogo entre os participantes.

A Secretaria Municipal de Meio Ambiente e Proteção Animal participou, na quarta-feira (24/4), do 2º Encontro das Unidades de Conservação da Serra do Itapeti, promovido pelo Instituto Ecofuturo e realizado no Parque Municipal Chiquinho Veríssimo. O evento reuniu representantes das unidades e promoveu um debate sobre a gestão, os desafios e propostas de trabalho, buscando pontos de convergência e ações conjuntas que podem ser adotadas no futuro.
As unidades de conservação da Serra do Itapeti são o Parque Municipal Chiquinho Veríssimo, localizado no alto da serra e administrado pela Prefeitura de Mogi das Cruzes; a Reserva Particular do Patrimônio Natural (RPPN) do Botujuru, administrada pelo Instituto Ecofuturo; e três áreas gerenciadas pelo governo paulista - a Estação Ecológica do Itapeti, a Área de Proteção Ambiental da Várzea do Tietê e a Área de Proteção Ambiental (APA) da Serra do Itapeti, que engloba todas as reservas.
A APA da Serra do Itapeti possui 5.138,94 hectares de área, dos quais 97% estão no município de Mogi das Cruzes. A área foi reconhecida em 2018, pelo Governo do Estado, e sua conservação e fiscalização compete aos órgãos estaduais, como a Fundação Florestal e a Polícia Ambiental.
Participaram do encontro secretária municipal de Meio Ambiente e Proteção Ambiental, Ionara Fernandes; o secretário-adjunto Daniel Teixeira de Lima; o diretor de sustentabilidade do Instituto Ecofuturo, Paulo Groke; a diretora da Fundação Florestal, Lucila Manzatti; as gestoras da Estação Ecológica do Itapeti, Mônica Gomes de Oliveira, e da RPPN Botujuru, Julia Krahenbuhl, além das professoras Maria Santina e Renata Scabbia (UMC). Também compareceram o comandante Gurgel e o tenente Edson, da Polícia Ambiental.
Ao longo do evento foram abordados temas como “Iniciativas municipais de Conservação na Serra do Itapeti”, “A participação da sociedade na gestão de Unidades de Conservação”, “Mogi Por Dentro na Serra do Itapeti: caminhos de um desenvolvimento estratégico e participativo do turismo local”, “Educação Ambiental na Estação Ecológica de Itapeti”, “A importância da pesquisa científica e a parceria com as universidades” e “A iniciativa privada na conservação de áreas naturais”, finalizando com um diálogo entre os participantes.
“Nubea de Portas Abertas” acontece neste sábado (14/3), com Feira de Adoção de Passeio do Bem
Vice-prefeito e equipe de Saúde se reúnem com médicos da Unica para alinhar melhorias no atendimento
Treze representantes da sociedade civil são eleitos para a gestão 2026-2028 do COMAS
Centro de Controle de Zoonoses de Mogi das Cruzes recebe prêmio nacional da Fiocruz
Estudantes conhecem processo de tratamento de água na  primeira visita do Semae de Portas Abertas 2026
Siga-nos nas redes sociais
Prefeitura de Mogi das Cruzes
Av. Ver. Narciso Yague Guimarães, 277
Centro Cívico
CEP 08780-900
Mogi das Cruzes/SP
Segunda a sexta, das 8 às 17 horas
Telefone: 4798-5000
Serviços: 162
Ouvidoria: 156
Semae: 115
Saúde: 160
Guarda Municipal: 153', 'Publicado', now());
INSERT INTO public.noticias (title, slug, content, status, published_at) VALUES ('Noticias 18c5c1', 'noticias-18c5c1', 'Secretaria de Meio Ambiente e Proteção Animal
O Junho Ambiental ofereceu um mês inteiro de programações, incluindo webinários sobre temas diversos, ações práticas de campo, como plantio de mudas e soltura de animais, além de parcerias firmadas entre o município e instituições reconhecidas. Este é o balanço realizado pela Secretaria Municipal do Verde e Meio Ambiente sobre o evento, que mobilizou professores, técnicos, especialistas de várias áreas de concentração, e principalmente a população mogiana, que participou ativamente de toda a programação.

 

A secretária municipal do Verde e Meio Ambiente, Michele de Sá Vieira, explica que os objetivos do Junho Ambiental foram alcançados. “Elaboramos a programação incluindo atividades que estivessem em conformidade com diversos públicos, objetivando a transmissão de informação, conhecimento e participação popular. Os eixos temáticos, apreciados no cotidiano das atividades da Secretaria, foram abordados no Junho Ambiental com o intuito de enfatizar o desenvolvimento sustentável, que é um pilar extremamente relevante da gestão do prefeito Caio e da vice Priscila Yamagami Kähler”, afirmou.

 

O eixos apontados pela secretária são Clima e Energia (incluindo mudanças climáticas e pesquisas ambientais), Licenciamento e Fiscalização (que aborda a análise e licenciamento ambiental, além da fiscalização ambiental), Saneamento Ambiental  (resíduos sólidos e macrodrenagem), Espaços Livres (unidades de conservação e proteção ambiental, espaços livres de lazer e sociabilidade, além de infraestrutura verde) e finalmente Educação Ambiental para Sociedades Sustentáveis (que inclui ações de educação ambiental).

 

Na prática, a programação do Junho Ambiental foi concebida para oferecer eventos que atendessem a todos esses eixos – o que aconteceu na prática. Além disso, parte dos assuntos abordados se interrelacionam com o planejamento do município para a certificação do Programa Município Verde Azul. 
A secretária lembra ainda que os eventos também foram estruturados para terem ligação com os Objetivos de Desenvolvimento Sustentável, um conjunto de 17 metas estabelecidas pela Organização das Nações Unidas (ONU) para o meio ambiente. “Trabalhamos sempre para criar programações que se associem às agendas ambientais contemporâneas”, frisa Michele.

 

Foram firmados termos de cooperação e parcerias com instituições como a Fundação Florestal, o ICLEI (Governos Locais pela Sustentabilidade), e a Associação Nacional de Municípios e Meio Ambiente (Anamma).

 

 Houve a participação de representantes de universidades como a Escola Superior de Agricultura “Luiz de Queiroz” (ESALQ/USP), o Instituto Nacional de Estudos e Pesquisas Educacionais (INPE), o Centro Universitário Braz Cubas, a Coordenadoria de Desenvolvimento Rural Sustentável (CDRS-SP) e o Instituto Suinã, assim como técnicos de órgãos municipais como o Centro de Controle de Zoonoses (CCZ) e a Escola Ambiental.
Colaboradores como produtores rurais, os apicultores e os produtores de insumos orgânicos também participaram da programação.

 

Os eventos registraram números expressivos. Os eventos online tiveram 287 curtidas e 1.984 visualizações. Já os plantios de mudas com eventos presenciais atraíram 328 pessoas e resultaram em 318 espécies plantadas. Já as doações de mudas totalizaram 428 espécies encaminhadas a cidadãos, todas com QR Code e cartilha de orientação, que traz informações sobre as espécies e os cuidados que devem ser tomados como cada uma.

O Junho Ambiental ofereceu um mês inteiro de programações, incluindo webinários sobre temas diversos, ações práticas de campo, como plantio de mudas e soltura de animais, além de parcerias firmadas entre o município e instituições reconhecidas. Este é o balanço realizado pela Secretaria Municipal do Verde e Meio Ambiente sobre o evento, que mobilizou professores, técnicos, especialistas de várias áreas de concentração, e principalmente a população mogiana, que participou ativamente de toda a programação.

 

A secretária municipal do Verde e Meio Ambiente, Michele de Sá Vieira, explica que os objetivos do Junho Ambiental foram alcançados. “Elaboramos a programação incluindo atividades que estivessem em conformidade com diversos públicos, objetivando a transmissão de informação, conhecimento e participação popular. Os eixos temáticos, apreciados no cotidiano das atividades da Secretaria, foram abordados no Junho Ambiental com o intuito de enfatizar o desenvolvimento sustentável, que é um pilar extremamente relevante da gestão do prefeito Caio e da vice Priscila Yamagami Kähler”, afirmou.

 

O eixos apontados pela secretária são Clima e Energia (incluindo mudanças climáticas e pesquisas ambientais), Licenciamento e Fiscalização (que aborda a análise e licenciamento ambiental, além da fiscalização ambiental), Saneamento Ambiental  (resíduos sólidos e macrodrenagem), Espaços Livres (unidades de conservação e proteção ambiental, espaços livres de lazer e sociabilidade, além de infraestrutura verde) e finalmente Educação Ambiental para Sociedades Sustentáveis (que inclui ações de educação ambiental).

 

Na prática, a programação do Junho Ambiental foi concebida para oferecer eventos que atendessem a todos esses eixos – o que aconteceu na prática. Além disso, parte dos assuntos abordados se interrelacionam com o planejamento do município para a certificação do Programa Município Verde Azul. 
A secretária lembra ainda que os eventos também foram estruturados para terem ligação com os Objetivos de Desenvolvimento Sustentável, um conjunto de 17 metas estabelecidas pela Organização das Nações Unidas (ONU) para o meio ambiente. “Trabalhamos sempre para criar programações que se associem às agendas ambientais contemporâneas”, frisa Michele.

 

Foram firmados termos de cooperação e parcerias com instituições como a Fundação Florestal, o ICLEI (Governos Locais pela Sustentabilidade), e a Associação Nacional de Municípios e Meio Ambiente (Anamma).

 

 Houve a participação de representantes de universidades como a Escola Superior de Agricultura “Luiz de Queiroz” (ESALQ/USP), o Instituto Nacional de Estudos e Pesquisas Educacionais (INPE), o Centro Universitário Braz Cubas, a Coordenadoria de Desenvolvimento Rural Sustentável (CDRS-SP) e o Instituto Suinã, assim como técnicos de órgãos municipais como o Centro de Controle de Zoonoses (CCZ) e a Escola Ambiental.
Colaboradores como produtores rurais, os apicultores e os produtores de insumos orgânicos também participaram da programação.

 

Os eventos registraram números expressivos. Os eventos online tiveram 287 curtidas e 1.984 visualizações. Já os plantios de mudas com eventos presenciais atraíram 328 pessoas e resultaram em 318 espécies plantadas. Já as doações de mudas totalizaram 428 espécies encaminhadas a cidadãos, todas com QR Code e cartilha de orientação, que traz informações sobre as espécies e os cuidados que devem ser tomados como cada uma.
“Nubea de Portas Abertas” acontece neste sábado (14/3), com Feira de Adoção de Passeio do Bem
Vice-prefeito e equipe de Saúde se reúnem com médicos da Unica para alinhar melhorias no atendimento
Treze representantes da sociedade civil são eleitos para a gestão 2026-2028 do COMAS
Centro de Controle de Zoonoses de Mogi das Cruzes recebe prêmio nacional da Fiocruz
Estudantes conhecem processo de tratamento de água na  primeira visita do Semae de Portas Abertas 2026
Siga-nos nas redes sociais
Prefeitura de Mogi das Cruzes
Av. Ver. Narciso Yague Guimarães, 277
Centro Cívico
CEP 08780-900
Mogi das Cruzes/SP
Segunda a sexta, das 8 às 17 horas
Telefone: 4798-5000
Serviços: 162
Ouvidoria: 156
Semae: 115
Saúde: 160
Guarda Municipal: 153', 'Publicado', now());
INSERT INTO public.posts_blog (title, slug, content, status, published_at) VALUES ('A Força da Reflexão Estratégica: O novo caminho do Suinã após o BTG Soma Meio Ambiente', 'a-forca-da-reflexao-estrategica-o-novo-caminho-do-suina-apos-o-btg-soma-meio-ambiente', 'Atuação
Publicações
Transparência
Doação
 
Ao longo de seis meses intensos em 2025, o Instituto Suinã integrou a 12ª edição do BTG Soma Meio Ambiente, programa de aceleração realizado pelo BTG Pactual em parceria com a AGO Social. Ser uma das 12 organizações selecionadas foi, sem dúvida, um reconhecimento do trabalho que desenvolvemos no território. Mas talvez o maior valor dessa participação tenha sido outro: a oportunidade, rara e necessária, de fazer a pausa estratégica que toda OSC precisa para crescer com intencionalidade.
Para quem não conhece, o BTG Soma Meio Ambiente é uma importante iniciativa de aceleração do banco  BTG Pactual, em parceria com a AGO Social, dedicada a fortalecer organizações que atuam na conservação da biodiversidade brasileira. Nossa equipe mergulhou em um programa intensivo, estruturado em três pilares: 
1) Aulas semanais com a rede Ago Social (focadas em Liderança, Gestão e Sustentabilidade Financeira); 
2) Mentoria individualizada com voluntários do BTG Pactual para diagnóstico de desafios; e 3) Desafios de aplicação prática com avaliação de bancas de especialistas.
 Foi essa estrutura robusta que nos permitiu concentrar 85 horas de encontros naquilo que é mais difícil no dia a dia: pensar o futuro com base em evidências e expertise de mercado.
A participação no programa BTG Soma para nós não foi apenas uma sequência de aulas e mentoria, mas um convite direto a olhar para dentro, com profundidade e coragem. No cotidiano de uma organização da sociedade civil, esse tempo de reflexão costuma ser engolido pelas demandas urgentes: atividades de campo, captação de recursos, operações que nunca param. A inovação mais relevante para o impacto, no entanto, nem sempre aparece em campo. Muitas vezes, ela nasce na mesa de planejamento.
Organizações da sociedade civil operam em cenários complexos e dinâmicos. O que definimos há dois ou três anos em nosso planejamento pode simplesmente não responder às urgências do presente. Às vezes porque o contexto mudou, outras porque a rotina absorve toda a energia operacional e impede que metas estratégicas ganhem vida.
Por isso, a pergunta essencial nunca foi “se” deveríamos revisar o plano estratégico, mas “quando e como” fazê-lo.
O programa proporcionou exatamente o que mais faltava: tempo dedicado, estrutura metodológica e especialistas capacitados para nos ajudar a recalcular a rota. Esse processo incluiu, sobretudo, a construção da Teoria da Mudança Institucional (TdM) : o mapa que liga nossas ações ao impacto que desejamos gerar. Sem essa bússola atualizada, qualquer organização corre o risco de operar no piloto automático, acumulando entregas, mas não necessariamente ampliando impacto.
O esforço e a dedicação de toda a equipe do Instituto Suinã, aliados ao conhecimento adquirido, nos permitiram alcançar resultados expressivos. Com grande satisfação, celebramos a realização de 30 metas definidas em nosso Plano de Desenvolvimento Institucional (PDI). Implementar mudanças na organização não é tarefa fácil, mas a abertura e o engajamento das equipes do Suinã foram cruciais para a absorção de novas ideias e processos ao longo de todo o processo.
Além das conquistas operacionais do nosso PDI, como a implementação de um novo sistema financeiro, contratação de uma estagiária para a área administrativa e diversificação de fontes de recurso para o Suinã, tivemos conquistas profundamente estratégicas:
Revisão participativa do Planejamento Estratégico: Garantindo que nossa visão de futuro esteja alinhada com os desafios emergentes.
Mapeamento e Criação de Indicadores Institucionais: com base na Teoria da Mudança, permitindo medir não só atividades, mas a qualidade do impacto;
Capital para Impulso: Saímos do programa com uma premiação de R$10 mil em recursos, que será investido diretamente para impulsionar a nova estratégia.
Ao investir em gestão, planejamento e métricas, ampliamos nossa capacidade de gerar impacto real e mensurável. A clareza estratégica não nos faz apenas crescer — ela multiplica nosso potencial.
Participar do BTG Soma justamente no ano em que celebramos 11 anos de atuação nos trouxe uma certeza: crescer de forma sustentável exige coragem para parar, refletir e ajustar os caminhos. Saímos desta jornada com uma gestão mais robusta, uma visão estratégica mais clara e um alinhamento profundo entre toda a equipe sobre a direção que queremos seguir até 2030.
Estamos mais preparados para medir nosso impacto, comunicar nossos resultados e, principalmente, tomar decisões com base em evidências e não em urgências.
Nossa experiência prova que a aceleração mais valiosa é aquela que capacita a organização não só a fazer mais, mas a fazer o que é certo, na hora certa, com a TdM e os indicadores mais adequados. Agradecemos ao BTG Pactual e à rede AGO Social por proporcionarem o tempo, a metodologia e o apoio necessários para esta transformação.
O Instituto Suinã entra em um novo ciclo. E o impacto que gerarmos a partir de agora será um reflexo direto dessa intencionalidade estratégica que escolhemos construir.
Suinã Instituto Socioambiental
Rua Capitão Alberto Aguiar Weisshon, 337 - Centro - Guararema/SP.
21.766.841/0001-84
contato@institutosuina.org
(12) 3965-0328
© 2024 Suinã Instituto Socioambiental', 'Publicado', now());
INSERT INTO public.posts_blog (title, slug, content, status, published_at) VALUES ('Avistando 2025: o que aprendemos com a campanha de financiamento coletivo e os desafios da captação no terceiro setor', 'avistando-2025-o-que-aprendemos-com-a-campanha-de-financiamento-coletivo-e-os-desafios-da-captacao-no-terceiro-setor', 'Atuação
Publicações
Transparência
Doação
 
A campanha de financiamento coletivo do Avistando 2025 foi um marco importante para o Instituto Suinã. Durante 51 dias, mobilizamos nossa rede, parceiros, amigos e apoiadores em torno da causa da observação de aves como ferramenta de educação ambiental, turismo sustentável e ciência cidadã. Ao final da campanha, alcançamos R$ 9.476,85 arrecadados pela plataforma Benfeitoria (já descontadas as taxas), além de outros apoios realizados fora da plataforma, e 91 doadores individuais se engajaram para viabilizar a próxima edição do evento.
Fonte: Márcio Gomes 
Avistando 2024 - Santa Branca/SP
Esse resultado, embora muito significativo, nos colocou diante de uma realidade que atravessa a maioria das Organizações da Sociedade Civil (OSCs) no Brasil: a dificuldade de captação de recursos e a fragilidade de sua sustentabilidade financeira. Nossa meta inicial era de R$ 25.000,00 e, embora tenhamos alcançado quase dez mil reais, não chegamos sequer à metade do valor esperado. Essa disparidade revela não um fracasso, mas sim a necessidade de refletirmos criticamente sobre os desafios estruturais do terceiro setor e sobre como podemos criar novas estratégias de mobilização de recursos.
Diversos estudos têm apontado que as OSCs no Brasil enfrentam uma dependência histórica de recursos internacionais, que, a partir dos anos 2000, começaram a diminuir de forma significativa (Da Silva et al. 2012). O motivo central foi a percepção de que o Brasil já possuía maior capacidade de autofinanciamento. Esse movimento gerou uma lacuna, pois os recursos nacionais não cresceram na mesma medida. Ao contrário, as doações internas ainda são restritas e fortemente concentradas em editais ou parcerias pontuais, o que deixa organizações como o Instituto Suinã constantemente vulneráveis.
O artigo O Terceiro Setor no Brasil: Avanços, Retrocessos e Desafios reforça que essa dependência de fontes instáveis gera descontinuidade de projetos e dificuldades para manter equipes, metodologias e impactos de longo prazo (Oliveira & Godói-de-Sousa. 2015). A ausência de uma política pública estruturada para o financiamento das OSCs coloca as organizações em um lugar frágil: sempre correndo atrás de recursos, sem conseguir investir de maneira consistente em planejamento estratégico.
Fonte: João Ferreira 
Avistando 2024 - Igaratá/SP 
No caso da campanha do Avistando, essa realidade se fez sentir. Tivemos engajamento, tivemos alcance, tivemos apoio, mas ainda assim não conseguimos mobilizar recursos na proporção da necessidade do evento. Isso mostra que a solidariedade comunitária é potente, mas precisa estar conectada a parcerias institucionais mais robustas.
Apesar do desafio, o que conquistamos foi grandioso. Cada um dos 91 apoiadores não apenas doou, mas também validou a importância do Avistando. Isso nos mostra que há uma base social comprometida com a causa e que reconhece o valor de iniciativas de educação ambiental e ciência cidadã. Esse capital simbólico é tão importante quanto o recurso financeiro, pois fortalece a legitimidade da organização e nos dá argumentos sólidos na busca por novos parceiros.
Fonte: Jhennifer Pires - Instituto Suinã
Jovens Observadores - Guararema/SP
A experiência nos leva a algumas reflexões que extrapolam o Avistando:
A necessidade de profissionalização da captação de recursos: Não podemos depender apenas de campanhas pontuais. É preciso estruturar processos contínuos, investir em marketing social e transparência, e diversificar as fontes de arrecadação.
A importância de parcerias locais: Empresas do território, que também se beneficiam da conservação ambiental e da boa imagem institucional, precisam reconhecer que apoiar projetos socioambientais é investir em um futuro comum.
O fortalecimento da cultura de doação no Brasil: Ainda há um longo caminho para construir uma sociedade que compreenda o ato de doar não como caridade, mas como corresponsabilidade socioambiental.
A articulação política e institucional: Para além das doações privadas, precisamos defender políticas públicas que assegurem linhas de financiamento permanentes para iniciativas da sociedade civil.
Queremos aproveitar este espaço para agradecer, de forma profunda, a cada pessoa que acreditou na campanha e fez sua contribuição. Sem vocês, não teríamos conseguido chegar até aqui. Mas queremos também fazer um convite: que essa colaboração não seja pontual, mas parte de um processo contínuo de fortalecimento do terceiro setor.
Afinal, como mostram os artigos que estudamos, o maior desafio não é realizar bons projetos, mas sustentá-los no tempo. O Instituto Suinã tem trabalhado com seriedade, transparência e compromisso com o território, mas precisa, como qualquer outra organização social, de uma rede de apoiadores forte e diversificada.
O Avistando é mais do que um evento de observação de aves. Ele é um movimento de valorização do território, de fortalecimento de comunidades e de conexão entre pessoas e natureza. Apoiar essa iniciativa é apoiar uma visão de futuro em que a conservação da biodiversidade, a geração de renda e a justiça climática caminham juntas.
Fonte: Jhennifer Pires - Instituto Suinã
Avistando 2024 - São Francisco Xavier/SP
Encerramos a campanha com menos da metade da meta, mas com a certeza de que demos um passo importante para transformar não só o Avistando, mas também a forma como pensamos e praticamos a captação de recursos no terceiro setor. Que esse aprendizado nos guie para parcerias mais sólidas, ações mais estratégicas e uma cultura de colaboração mais enraizada em nossa sociedade.
Um agradecimento especial à SAVE Brasil, nossa parceira na realização da campanha de financiamento coletivo. O apoio e articulação foram fundamentais para mobilizar pessoas e ampliar o alcance da causa. Essa parceria reafirma a importância de trabalharmos em rede: quando instituições unem forças em torno de um propósito comum, como a conservação da biodiversidade e o fortalecimento comunitário, o impacto é maior e mais transformador.
OLIVEIRA, Eider Arantes; GODÓI-DE-SOUSA, Edileusa. O Terceiro Setor no Brasil: avanços, retrocessos e desafios para as Organizações Sociais. RIS–Revista Interdisciplinar de Gestão Social, v. 4, n. 3, p. 181-199, 2015.
DA SILVA, Elton Praxedes Carvalho et al. Captação de recursos para a gestão do terceiro setor, um grande desafio. Editora, local, 2012.
Suinã Instituto Socioambiental
Rua Capitão Alberto Aguiar Weisshon, 337 - Centro - Guararema/SP.
21.766.841/0001-84
contato@institutosuina.org
(12) 3965-0328
© 2024 Suinã Instituto Socioambiental', 'Publicado', now());
INSERT INTO public.posts_blog (title, slug, content, status, published_at) VALUES ('Jovens Observadores: educação ambiental como caminho para o pertencimento e o turismo sustentável', 'jovens-observadores-educacao-ambiental-como-caminho-para-o-pertencimento-e-o-turismo-sustentavel', 'Atuação
Publicações
Transparência
Doação
 
Atualizado: 11 de ago. de 2025
A educação ambiental, quando construída a partir das vivências, do território e da escuta ativa, torna-se uma potente ferramenta de transformação social. É com esse princípio que o Projeto Jovens Observadores foi concebido e executado pelo Instituto Suinã nos municípios de Jacareí e Guararema (SP), ao longo de nove meses de projeto. Com foco inicial em juventudes residentes em áreas periféricas e com pouca oferta de atividades educativas extracurriculares, o projeto propôs um percurso formativo pautado na observação de aves como porta de entrada para temas como conservação da biodiversidade, turismo sustentável e os chamados empregos verdes.
O projeto foi estruturado em encontros formativos híbridos (presenciais e online), saídas de campo para áreas naturais estratégicas do território, como o Parque das Neblinas em Mogi das Cruzes, o Parque Estadual da Serra do Mar núcleo Caraguatatuba e áreas de agroecologia, sendo realizadas atividades de leitura crítica do território a partir do olhar da fauna, da paisagem e das práticas comunitárias locais. Durante essa jornada, os participantes foram incentivados a construir roteiros ecoturísticos autorais, refletindo sobre as interações possíveis entre natureza, cultura, economia e pertencimento.
Metodologia fundamentada na escuta, no vínculo e na prática
A metodologia do projeto teve como base a educação ambiental crítica, integrando aspectos cognitivos, sensoriais e afetivos no processo de formação. Conforme define a Lei nº 9.795/99 (Art. 1º), a educação ambiental deve ser um componente permanente da educação, integrando-se a todos os níveis e modalidades de ensino, tanto no contexto formal quanto no não formal. Alinhado a esse princípio, o Jovens Observadores desenvolveu atividades que promoveram o protagonismo juvenil, com estímulo à valorização das memórias e referências locais dos participantes, articuladas com a experiência prática da observação de aves e da interpretação ambiental.
Além disso, é importante compreender que o fortalecimento da educação ambiental exige integração entre conhecimentos ecológicos e políticas públicas, e que sua efetividade está diretamente relacionada à transformação cultural e de valores sociais, especialmente no modo como a sociedade interage com os bens naturais (Oliveira Júnior & Sato, 2006).
Outro ponto-chave da metodologia foi a adoção de ferramentas da ciência cidadã, como o uso do aplicativo eBird, que permitiu que os participantes registrassem as espécies observadas, contribuindo com dados reais para redes de monitoramento e conservação. A ciência cidadã é reconhecida como uma estratégia essencial para ampliar o acesso ao conhecimento científico, permitindo experiências de descoberta e engajamento que beneficiam tanto os participantes quanto a ciência (Riesch & Potter, 2014; Sullivan et al., 2017; Mamede, Benites & Alho, 2017). Mesmo que esses participantes não analisem dados ou publiquem artigos científicos, cidadãos cientistas exercem um papel fundamental na coleta de informações e contribuem de forma efetiva para questões ambientais globais (Cooper et al., 2007; Cohn, 2008).
Essa abordagem fortalece o vínculo entre as pessoas e a natureza, despertando não apenas o interesse pelo meio ambiente, mas também um comprometimento real com sua proteção e conservação (Mamede, Benites & Alho, 2017).
Resultados e aprendizados
Os impactos do projeto se revelaram em diferentes níveis. No plano individual, muitos participantes relataram mudanças significativas na forma como enxergam os espaços naturais e as possibilidades profissionais na área ambiental. No plano coletivo, houve um fortalecimento da rede de parcerias locais, com escolas, secretarias municipais, unidades de conservação e coletivos ambientais contribuindo ativamente para a realização das atividades.
A qualidade e o impacto da experiência vivenciada pelos participantes também se refletiram na avaliação final do projeto. Quando perguntados "Como você avalia sua experiência geral no Projeto Jovens Observadores?", 93% dos respondentes atribuíram nota máxima (5 de 5 pontos). Esse indicador demonstra não apenas a aceitação da proposta metodológica, mas também a sua potência transformadora. A alta taxa de satisfação sugere que os participantes reconheceram valor nas vivências proporcionadas, na escuta ativa, nas conexões territoriais e no contato com a natureza, elementos que fortalecem o pertencimento e ampliam horizontes formativos e profissionais.
Cabe destacar que, embora o público-alvo inicial fossem jovens do ensino médio, o projeto acolheu também participantes de outras faixas etárias, denominados “veteranos”, cuja adesão foi especialmente significativa no município de Guararema. Essa flexibilidade metodológica contribuiu para ampliar o alcance do projeto e reforçar que o desejo de reconexão com a natureza atravessa gerações.
Educação ambiental como política pública transversal
A experiência do Projeto Jovens Observadores demonstra que a educação ambiental, quando pensada a partir das potencialidades do território, pode se tornar um caminho efetivo para a conservação da biodiversidade, a geração de renda e o fortalecimento das identidades locais.
É importante destacar que o projeto derivou diretamente do evento "Avistando", iniciativa intermunicipal de observação de aves, onde desde 2022 o Instituto Suinã atua como parte do corpo articulador do evento. Com abrangência nos territórios do Vale do Paraíba, Litoral Norte e Alto Tietê, o Avistando se consolidou como um evento referência na temática da avifauna e da sensibilização ambiental na região.
A partir das vivências promovidas pelo Avistando, identificou-se a necessidade de ampliar e aprofundar as ações com foco no vínculo sociedade e natureza que a observação de aves proporciona, especialmente no que se refere à formação crítica e ao estímulo ao ecoturismo como vetor de geração de renda associado à conservação da biodiversidade. O Projeto Jovens Observadores nasce, portanto, como uma resposta metodológica concreta a essa demanda, fortalecendo o olhar local sobre o turismo de natureza como campo legítimo de atuação profissional e de construção de pertencimento ambiental.
A estratégia adotada no projeto também dialoga com os Objetivos de Desenvolvimento Sustentável (ODS), especialmente os ODS 4 (Educação de Qualidade), ODS 8 (Trabalho Decente e Crescimento Econômico), ODS 12 (Consumo e Produção Responsáveis) e ODS 15 (Vida Terrestre).
Mais do que apresentar a observação de aves, o projeto buscou formar observadores de si, do outro e do lugar onde se vive. E isso, para o Instituto Suinã, é a essência da educação ambiental com impacto real: não apenas informar, mas transformar.
Autora
Lorrane Coelho, caiçara de origem, bióloga especialista em Educação Ambiental e Sustentabilidade e apaixonada pela educação como caminho de reconexão entre pessoas e natureza. Trocou a areia nos pés pelo barro na bota ao se mudar para o Vale do Paraíba onde atua em projetos de Educação Ambiental.
Referências
 COHN, Jeffrey P. Citizen science: Can volunteers do real research?. BioScience, v. 58, n. 3, p. 192-197, 2008.
COOPER, Caren B. et al. Citizen science as a tool for conservation in residential ecosystems. Ecology and Society, v. 12, n. 2, 2007.
LEI Nº 9.795, DE 27 DE ABRIL DE 1999. Dispõe sobre a educação ambiental, institui a Política Nacional de Educação Ambiental e dá outras providências.
MAMEDE, Simone; BENITES, Maristela; ALHO, Cleber José Rodrigues. Ciência cidadã e sua contribuição na proteção e conservação da biodiversidade na reserva da biosfera do Pantanal. Revista Brasileira de Educação Ambiental (RevBEA), v. 12, n. 4, p. 153-164, 2017.
OLIVEIRA JÚNIOR, Samuel Borges de; SATO, Michèle. Educação ambiental e etnoconhecimento: parceiros para a conservação da diversidade de aves pantaneiras. 2006.
RIESCH, Hauke; POTTER, Clive. Citizen science as seen by scientists: Methodological, epistemological and ethical dimensions. Public Understanding of Science, v. 23, n. 1, p. 107-120, 2014.
SULLIVAN, Brian L. et al. Using open access observational data for conservation action: A case study for birds. Biological Conservation, v. 208, p. 5-14, 2017.
Suinã Instituto Socioambiental
Rua Capitão Alberto Aguiar Weisshon, 337 - Centro - Guararema/SP.
21.766.841/0001-84
contato@institutosuina.org
(12) 3965-0328
© 2024 Suinã Instituto Socioambiental', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('276Ee571042544Be8F2Fc030B9Ec8Dca', '276ee571042544be8f2fc030b9ec8dca', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_276ee571042544be8f2fc030b9ec8dca.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('45C0F9Bd5C5F4D4B83747Cc04686C1F7', '45c0f9bd5c5f4d4b83747cc04686c1f7', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_45c0f9bd5c5f4d4b83747cc04686c1f7.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('Bb5Da44Be18345Bfa2A8Cb5806Af227F', 'bb5da44be18345bfa2a8cb5806af227f', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_bb5da44be18345bfa2a8cb5806af227f.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('654A77F3398F4Ad0Aa455Ec74A3596Bb', '654a77f3398f4ad0aa455ec74a3596bb', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_654a77f3398f4ad0aa455ec74a3596bb.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('7Ac1D1Cc914C49188442Fa791Dbc1538', '7ac1d1cc914c49188442fa791dbc1538', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_7ac1d1cc914c49188442fa791dbc1538.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('5A815C8D75C142Bda290C6640A6Acc62', '5a815c8d75c142bda290c6640a6acc62', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_5a815c8d75c142bda290c6640a6acc62.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('A814B0D43Ab8453Abf6E77Cbc01B2C1C', 'a814b0d43ab8453abf6e77cbc01b2c1c', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_a814b0d43ab8453abf6e77cbc01b2c1c.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('C8A459E90Cd04952A27C7F5B8114297D', 'c8a459e90cd04952a27c7f5b8114297d', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_c8a459e90cd04952a27c7f5b8114297d.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('2Df34F0078Fe4E37A15Fd57Ae0A838C6', '2df34f0078fe4e37a15fd57ae0a838c6', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_2df34f0078fe4e37a15fd57ae0a838c6.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('F17D2E0223B241B5B961E057E4Dcb2B0', 'f17d2e0223b241b5b961e057e4dcb2b0', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_f17d2e0223b241b5b961e057e4dcb2b0.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('81C749D5Cd194Cd1Ac084638377A1A79', '81c749d5cd194cd1ac084638377a1a79', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_81c749d5cd194cd1ac084638377a1a79.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('0Ddcacb27C304Dedb13A039De517C2A8', '0ddcacb27c304dedb13a039de517c2a8', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_0ddcacb27c304dedb13a039de517c2a8.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('79F73A38C529417690Ba4A53B769B96E', '79f73a38c529417690ba4a53b769b96e', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_79f73a38c529417690ba4a53b769b96e.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('Cee2Aa89460B48C0Ab175C1D3D734C7E', 'cee2aa89460b48c0ab175c1d3d734c7e', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_cee2aa89460b48c0ab175c1d3d734c7e.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('F2Bd178B910B4C8Fad5Bb9402525E511', 'f2bd178b910b4c8fad5bb9402525e511', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_f2bd178b910b4c8fad5bb9402525e511.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('B2F45522F7C6403C834A60F180A87218', 'b2f45522f7c6403c834a60f180a87218', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_b2f45522f7c6403c834a60f180a87218.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('D0155C5Cc90F46438E2D98B62Dab285C', 'd0155c5cc90f46438e2d98b62dab285c', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_d0155c5cc90f46438e2d98b62dab285c.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('05Df97Af4C3B47E08F8Cfdcdcf75F02B', '05df97af4c3b47e08f8cfdcdcf75f02b', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_05df97af4c3b47e08f8cfdcdcf75f02b.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('7F235Bbddd70477B85400497B094503A', '7f235bbddd70477b85400497b094503a', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_7f235bbddd70477b85400497b094503a.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('1E7E42E640A8438F9D01Bca19Da53116', '1e7e42e640a8438f9d01bca19da53116', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_1e7e42e640a8438f9d01bca19da53116.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('F6200Edd23A745Ca9F3F765E32438A57', 'f6200edd23a745ca9f3f765e32438a57', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_f6200edd23a745ca9f3f765e32438a57.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('07Ffa05D55904A7F818409B2Eb3976D1', '07ffa05d55904a7f818409b2eb3976d1', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_07ffa05d55904a7f818409b2eb3976d1.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('9D52442Aded74Aa49853C6C27Fb4D2Ae', '9d52442aded74aa49853c6c27fb4d2ae', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_9d52442aded74aa49853c6c27fb4d2ae.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('F6E556Cd7D5F46B88883Bf91631Ac3Cc', 'f6e556cd7d5f46b88883bf91631ac3cc', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_f6e556cd7d5f46b88883bf91631ac3cc.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('46Cfb85Bc45A4C969586E8Cd76B75768', '46cfb85bc45a4c969586e8cd76b75768', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_46cfb85bc45a4c969586e8cd76b75768.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('46Cfb85Bc45A4C969586E8Cd76B75768', '46cfb85bc45a4c969586e8cd76b75768-e7b94', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_46cfb85bc45a4c969586e8cd76b75768.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('C37E71E3B4244491A7C06D8F34E6C0C0', 'c37e71e3b4244491a7c06d8f34e6c0c0', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_c37e71e3b4244491a7c06d8f34e6c0c0.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('887710623E2C4B85928A5D4F4E682641', '887710623e2c4b85928a5d4f4e682641', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_887710623e2c4b85928a5d4f4e682641.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('3A30E23Fbd1D4Edba62748665736E837', '3a30e23fbd1d4edba62748665736e837', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_3a30e23fbd1d4edba62748665736e837.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('261Ca29Acf5F42E89A8Ee7Acb2Be2223', '261ca29acf5f42e89a8ee7acb2be2223', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_261ca29acf5f42e89a8ee7acb2be2223.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('26Ae831F5B1A46Df97A068F24E5F494B', '26ae831f5b1a46df97a068f24e5f494b', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_26ae831f5b1a46df97a068f24e5f494b.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('22Df35F30Bca4D088E3Ef9D86984C8Ac', '22df35f30bca4d088e3ef9d86984c8ac', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_22df35f30bca4d088e3ef9d86984c8ac.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('E454D740Abf24A29Be4E38382Fcfb003', 'e454d740abf24a29be4e38382fcfb003', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_e454d740abf24a29be4e38382fcfb003.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('6B8C0Aea9C7D40A6Bf0De06F3286B822', '6b8c0aea9c7d40a6bf0de06f3286b822', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_6b8c0aea9c7d40a6bf0de06f3286b822.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('1B2Eb31B68974Ca8859825Db02Cdf0A4', '1b2eb31b68974ca8859825db02cdf0a4', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_1b2eb31b68974ca8859825db02cdf0a4.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('186A941F867647C3Ba63Febde02A3262', '186a941f867647c3ba63febde02a3262', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_186a941f867647c3ba63febde02a3262.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('Fcb8796Ecc95453Fb09A109E19B2F209', 'fcb8796ecc95453fb09a109e19b2f209', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_fcb8796ecc95453fb09a109e19b2f209.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('Cbdaacd9F9E841Ff8A5F39041Ad5E793', 'cbdaacd9f9e841ff8a5f39041ad5e793', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_cbdaacd9f9e841ff8a5f39041ad5e793.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('1B2Eb31B68974Ca8859825Db02Cdf0A4', '1b2eb31b68974ca8859825db02cdf0a4-8f5e9', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_1b2eb31b68974ca8859825db02cdf0a4.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('A2D1891082D34933Bcbd59368A832390', 'a2d1891082d34933bcbd59368a832390', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_a2d1891082d34933bcbd59368a832390.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('B4Df77404Cbc412693F3A3Acfbbff382', 'b4df77404cbc412693f3a3acfbbff382', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_b4df77404cbc412693f3a3acfbbff382.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('1B2Eb31B68974Ca8859825Db02Cdf0A4', '1b2eb31b68974ca8859825db02cdf0a4-f7ab7', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_1b2eb31b68974ca8859825db02cdf0a4.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('0C3B9F37126F47Ddbcd0C9721F8A6C53', '0c3b9f37126f47ddbcd0c9721f8a6c53', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_0c3b9f37126f47ddbcd0c9721f8a6c53.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('2432D643Df774A06A7956D3345F58420', '2432d643df774a06a7956d3345f58420', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_2432d643df774a06a7956d3345f58420.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('F9A9Cea09B7C4D12Bb8C4Bcfb3E43D88', 'f9a9cea09b7c4d12bb8c4bcfb3e43d88', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_f9a9cea09b7c4d12bb8c4bcfb3e43d88.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('Ec1F25163D8D441Ea22333Eba65306B2', 'ec1f25163d8d441ea22333eba65306b2', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_ec1f25163d8d441ea22333eba65306b2.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('7472A7D03B5E47D99B51D8C1E00393Bc', '7472a7d03b5e47d99b51d8c1e00393bc', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_7472a7d03b5e47d99b51d8c1e00393bc.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('Efec792Aadab4Ebbad0196842C41F260', 'efec792aadab4ebbad0196842c41f260', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_efec792aadab4ebbad0196842c41f260.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('F9A9Cea09B7C4D12Bb8C4Bcfb3E43D88', 'f9a9cea09b7c4d12bb8c4bcfb3e43d88-b4ce4', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_f9a9cea09b7c4d12bb8c4bcfb3e43d88.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('0Bc1505266604E658A7Dafc7Ba366F87', '0bc1505266604e658a7dafc7ba366f87', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_0bc1505266604e658a7dafc7ba366f87.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('5Fc5E2884A1A4E9F8659312D4Cecb243', '5fc5e2884a1a4e9f8659312d4cecb243', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_5fc5e2884a1a4e9f8659312d4cecb243.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('145A34Ac79D342668F8A36F54Ca745F5', '145a34ac79d342668f8a36f54ca745f5', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_145a34ac79d342668f8a36f54ca745f5.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('0B8508Cadc25406A82D6870F1F6553Cc', '0b8508cadc25406a82d6870f1f6553cc', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_0b8508cadc25406a82d6870f1f6553cc.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('474D169B5C1843Debc27C479C48610Ca', '474d169b5c1843debc27c479c48610ca', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_474d169b5c1843debc27c479c48610ca.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('474D169B5C1843Debc27C479C48610Ca', '474d169b5c1843debc27c479c48610ca-8318d', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_474d169b5c1843debc27c479c48610ca.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('4C916B69E51040Eb89B5Eda6A173A851', '4c916b69e51040eb89b5eda6a173a851', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_4c916b69e51040eb89b5eda6a173a851.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('1Ce9Eebe379540F584C33757Fbad151A', '1ce9eebe379540f584c33757fbad151a', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_1ce9eebe379540f584c33757fbad151a.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('576E8E873Cf242D2B023Abe69852357C', '576e8e873cf242d2b023abe69852357c', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_576e8e873cf242d2b023abe69852357c.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('1A20163403784E488Fc89277F55Aadaa', '1a20163403784e488fc89277f55aadaa', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_1a20163403784e488fc89277f55aadaa.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('7400C7430C73422Fbcaf45E748A27B33', '7400c7430c73422fbcaf45e748a27b33', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_7400c7430c73422fbcaf45e748a27b33.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('0B8508Cadc25406A82D6870F1F6553Cc', '0b8508cadc25406a82d6870f1f6553cc-c25db', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_0b8508cadc25406a82d6870f1f6553cc.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('521753176F0F4B21Bb93A8Cd547D84Fb', '521753176f0f4b21bb93a8cd547d84fb', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_521753176f0f4b21bb93a8cd547d84fb.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.editais (title, slug, content, status, published_at) VALUES ('484D99A932794F26Bf1982Ac5Fd638Da', '484d99a932794f26bf1982ac5fd638da', '<p><a href="https://novo.institutosuina.org/_files/ugd/e2b488_484d99a932794f26bf1982ac5fd638da.pdf" target="_blank">Visualizar Edital (PDF)</a></p>', 'Publicado', now());
INSERT INTO public.relatorios (title, file_url, description) VALUES ('27B2067736854445Bcd46Cd2B24A00Ef', 'https://novo.institutosuina.org/_files/ugd/e2b488_27b2067736854445bcd46cd2b24a00ef.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('4Ecc4Ec2230A4658Bf6E32Deef414305', 'https://novo.institutosuina.org/_files/ugd/e2b488_4ecc4ec2230a4658bf6e32deef414305.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('0E4B5Ae165E143Ea9027F0Cf13A2Ebc8', 'https://novo.institutosuina.org/_files/ugd/e2b488_0e4b5ae165e143ea9027f0cf13a2ebc8.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('1E98E38Faa81410Ca1254D47Dedd1C3A', 'https://novo.institutosuina.org/_files/ugd/e2b488_1e98e38faa81410ca1254d47dedd1c3a.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('0E8C842C195148Bdb5313F6E0Ecd0C3D', 'https://novo.institutosuina.org/_files/ugd/e2b488_0e8c842c195148bdb5313f6e0ecd0c3d.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('9Cd284822Fa44476B86F1D9418Bfb58D', 'https://novo.institutosuina.org/_files/ugd/e2b488_9cd284822fa44476b86f1d9418bfb58d.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('A2B0Ab6Bb5594D8Cb54E4980Bf5B7Cc7', 'https://novo.institutosuina.org/_files/ugd/e2b488_a2b0ab6bb5594d8cb54e4980bf5b7cc7.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('17Fd3013Dab24B37A9A38Af67Ff03969', 'https://novo.institutosuina.org/_files/ugd/e2b488_17fd3013dab24b37a9a38af67ff03969.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('32Db07136B6D475399541Ee99Fa07B38', 'https://novo.institutosuina.org/_files/ugd/e2b488_32db07136b6d475399541ee99fa07b38.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('D74413C4E3Cf4A25Af93548E9Cc24Bcf', 'https://novo.institutosuina.org/_files/ugd/e2b488_d74413c4e3cf4a25af93548e9cc24bcf.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('Fb950910208C45Ef9Cf2E03A7095Ed52', 'https://novo.institutosuina.org/_files/ugd/e2b488_fb950910208c45ef9cf2e03a7095ed52.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('8C46F01A469640A18303038C0Bccc895', 'https://novo.institutosuina.org/_files/ugd/e2b488_8c46f01a469640a18303038c0bccc895.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('D78Ffdf706C44Dada463Dcfba263435A', 'https://novo.institutosuina.org/_files/ugd/e2b488_d78ffdf706c44dada463dcfba263435a.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('79847F2048A14D32Bdd2E252F7Fc8Bbe', 'https://novo.institutosuina.org/_files/ugd/e2b488_79847f2048a14d32bdd2e252f7fc8bbe.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('2385106E3B754F08B5A866Efacc2Ff4E', 'https://novo.institutosuina.org/_files/ugd/e2b488_2385106e3b754f08b5a866efacc2ff4e.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('1499586E8C5749C2948E2543Fe42B345', 'https://novo.institutosuina.org/_files/ugd/e2b488_1499586e8c5749c2948e2543fe42b345.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('3182E933486947D8Bbcc62555Bbf48E4', 'https://novo.institutosuina.org/_files/ugd/e2b488_3182e933486947d8bbcc62555bbf48e4.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('9F917Bddd3B64Aa0A12044C5A40Ee7De', 'https://novo.institutosuina.org/_files/ugd/e2b488_9f917bddd3b64aa0a12044c5a40ee7de.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('E5Db31946Bae4A5Da54E1B1E39303A67', 'https://novo.institutosuina.org/_files/ugd/e2b488_e5db31946bae4a5da54e1b1e39303a67.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('D46Fe64752E4471Db57Aa28Ae69A40C3', 'https://novo.institutosuina.org/_files/ugd/e2b488_d46fe64752e4471db57aa28ae69a40c3.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('039C45752588419Fb3991F1E33F2Cba7', 'https://novo.institutosuina.org/_files/ugd/e2b488_039c45752588419fb3991f1e33f2cba7.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('F9152Badbd314139Afcd99100D7Ab262', 'https://novo.institutosuina.org/_files/ugd/e2b488_f9152badbd314139afcd99100d7ab262.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('592E1C33F94A4Bfc8189061443Bdbf20', 'https://novo.institutosuina.org/_files/ugd/e2b488_592e1c33f94a4bfc8189061443bdbf20.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('Deeae90Aefc34Eb289Cb931D7Ffef5A6', 'https://novo.institutosuina.org/_files/ugd/e2b488_deeae90aefc34eb289cb931d7ffef5a6.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('91Ed5D03Ed38439Cb475Cc25Ee1F7544', 'https://novo.institutosuina.org/_files/ugd/e2b488_91ed5d03ed38439cb475cc25ee1f7544.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('D37D0089Fb954F0Baf749Eb19Ba42919', 'https://novo.institutosuina.org/_files/ugd/e2b488_d37d0089fb954f0baf749eb19ba42919.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('8C0F2D4Ed86048739Bcc36829Ef0A9E8', 'https://novo.institutosuina.org/_files/ugd/e2b488_8c0f2d4ed86048739bcc36829ef0a9e8.pdf', 'Importado do site antigo');
INSERT INTO public.relatorios (title, file_url, description) VALUES ('989F642Fb82E49Ec9B65Da806662B5A0', 'https://novo.institutosuina.org/_files/ugd/e2b488_989f642fb82e49ec9b65da806662b5a0.pdf', 'Importado do site antigo');